---
title: "git_01"
author: "Dom Ciriello"
date: "Spring 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

The day was wet, the rain fell souse  
Like jars of strawberry jam, a  
sound was heard in the old henhouse,  
A beating of a hammer.  
Of stalwart form, and visage warm,  

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

To Ridgely Torrence  
On Last Looking into His 'Hesperides'  
I often see flowers from a passing car  
That are gone before I can tell what they are.  
I want to get out of the train and go back  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

"The sun was shining on the sea,  
      Shining with all his might:  
He did his very best to make  
      The billows smooth and bright —  
And this was odd, because it was  
      The middle of the night.  
  
The moon was shining sulkily,  
      Because she thought the sun  
Had got no business to be there  
      After the day was done —  
"It's very rude of him," she said,  
      "To come and spoil the fun."  

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->

'A man should write to please himself,'  
 He proudly said.  
Well, see his poems on the shelf,  
 Dusty, unread.  
  
When he came to my shop each day,  
 So peaked and cold,  
I'd sneak one of his books away  
 And say 'twas sold.  
  
And then by chance he looked below,  
 And saw a stack  
Of his own work,--speechless with woe  
 He came not back.  
  
I hate to think he took to drink,  
 And passed away;  
I have not heard of him a word  
 Unto this day.  
  
A man must write to please himself,  
 Of all it's true;  
But happy they who spurning pelf--  
 Please people too.  
  
